[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/Adafruit GFX Library @ ^1.11.11
    adafruit/Adafruit ILI9341 @ ^1.6.1
    links2004/WebSockets @ ^2.4.1
    bblanchon/ArduinoJson @ ^6.21.0
